apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-pdb
  namespace: autoserve
  labels:
    app: frontend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: frontend

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-pdb
  namespace: autoserve
  labels:
    app: backend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: backend

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: worker-pdb
  namespace: autoserve
  labels:
    app: worker
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: worker

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ml-controller-pdb
  namespace: autoserve
  labels:
    app: ml-controller
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ml-controller
