apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: autoserve
  namespace: argocd
  labels:
    app: autoserve
spec:
  description: AutoServe microservices platform
  sourceRepos:
    - 'https://github.com/your-org/autoserve'
  destinations:
    - namespace: 'autoserve-*'
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
  namespaceResourceWhitelist:
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
    - group: ''
      kind: Service
    - group: ''
      kind: ServiceAccount
    - group: apps
      kind: Deployment
    - group: apps
      kind: ReplicaSet
    - group: autoscaling
      kind: HorizontalPodAutoscaler
    - group: networking.k8s.io
      kind: Ingress
    - group: networking.k8s.io
      kind: NetworkPolicy
    - group: policy
      kind: PodDisruptionBudget
    - group: rbac.authorization.k8s.io
      kind: Role
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
  roles:
    - name: autoserve-admin
      description: Admin access to AutoServe project
      policies:
        - p, proj:autoserve:autoserve-admin, applications, *, autoserve/*, allow
        - p, proj:autoserve:autoserve-admin, logs, get, autoserve/*, allow
        - p, proj:autoserve:autoserve-admin, exec, create, autoserve/*, allow
      groups:
        - autoserve:admin
    - name: autoserve-developer
      description: Developer access to AutoServe project
      policies:
        - p, proj:autoserve:autoserve-developer, applications, get, autoserve/*, allow
        - p, proj:autoserve:autoserve-developer, applications, sync, autoserve/*, allow
        - p, proj:autoserve:autoserve-developer, logs, get, autoserve/*, allow
      groups:
        - autoserve:developer
  syncWindows:
    - kind: allow
      schedule: '* * * * *'
      duration: 24h
      applications:
        - autoserve-dev
    - kind: deny
      schedule: '0 22 * * *'
      duration: 8h
      applications:
        - autoserve-prod
      manualSync: true
